swagger: "2.0"
info:
  version: 1.0.0
  title: "astronauti"
  description: Assignment API
  termsOfService: http://swagger.io/terms/
  contact:
    name: Swagger API Team
    email: foo@example.com
    url: http://madskristensen.net
  license:
    name: MIT
    url: http://github.com/gruntjs/grunt/blob/master/LICENSE-MIT
host: petstore.swagger.io
basePath: /api
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /assignments:
    get:
      description: |
        Returns all the assignments from the system 
      operationId: returnAssignments
      responses:
        200:
          description: assignment response
          schema:
            type: array
            items:
              $ref: '#/definitions/Assignment'
    post:
      description: Creates a new assignment.  Duplicates are allowed
      operationId: addAssignment
      parameters:
        - name: assignment
          in: body
          description: Assignment to upload
          required: true
          schema:
            $ref: '#/definitions/NewAssignment'
      responses:
        200:
          description: pet response
          schema:
            $ref: '#/definitions/Assignment'
  /assignments/{assignmentId}:
    get:
      description: Returns a single assignment information
      operationId: find assignment by id
      parameters:
        - name: assignmentId
          in: path
          description: ID of assignment to fetch
          required: true
          type: string
      responses:
        200:
          description: OK - response
          schema:
            $ref: '#/definitions/Assignment'
        404:
          description: Not found
          schema:
            $ref: '#/definitions/Error'
    delete:
      description: deletes a single assignment based on the ID supplied
      operationId: deleteAssignment
      parameters:
        - name: assignmentId
          in: path
          description: ID of assignment to delete
          required: true
          type: string
      responses:
        204:
          description: assignment deleted
        404:
          description: Not found
          schema:
            $ref: '#/definitions/Error'
    put:
      description: modify a single assignment based on the ID supplied
      operationId: putAssignment
      parameters:
        - name: assignmentId
          in: path
          description: ID of assignment to delete
          required: true
          type: string
      responses:
        200:
          description: OK - response
        404:
          description: Not found
          schema:
            $ref: '#/definitions/Error'
definitions:
  Assignment:
    allOf:
      - $ref: '#/definitions/NewAssignment'
      - required:
        - assignmentResult
        properties:
          assignmentResult:
            type: object
  NewAssignment:
    required:
      - assignmentID
      - workerID
    properties:
      assignmentID:
        type: string
      workerID:
        type: string
  Error:
    required:
      - code
      - message
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string